name: Lua

on:
  push: {}

permissions:
  id-token: write
  contents: write

jobs:
  LuaCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Luacheck
        uses: lunarmodules/luacheck@v1.2.0
        with:
          args: "init.lua lua/*"
